[font]
normal = { family = "JetbrainsMono Nerd Font", style = "ExtraLight" }
size = 14

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]

[env]
TERM = "xterm-256color"

