unbind r
bind r source-file ~/.tmux.conf

unbind C-b
set -g prefix C-s
bind C-s send-prefix

set -g mouse on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set-option -g status-position top
set -g focus-events on

# Set new panes to open in current directory
bind c new-window -c "#{pane_current_path}"

bind C-o split-window -h -p 33 -c "#{pane_current_path}" "opencode"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "none"
set -g @catppuccin_status_background "#0d1721"
set -g @custom_window_current_icon_color "#{?#{==:#{pane_current_command},zsh},#[fg=#{@thm_sapphire}],#{?#{m/r:^n?vim$,#{pane_current_command}},#[fg=#{@thm_green}],#[fg=#{@thm_peach}]}}"
set -g window-status-format " #[fg=#{@thm_overlay_1}]#(bash ~/.config/tmux/nerdfont_numbers.sh '#I' 'dsquare')"
set -ga window-status-format "#[default]#[nobold]#{?#{==:#{window_name},window},#{pane_current_command},#W}#[default] "

set -g window-status-current-format " #{E:@custom_window_current_icon_color}"
set -ga window-status-current-format "#(bash ~/.config/tmux/nerdfont_numbers.sh '#I' 'msquare')"
set -ga window-status-current-format "#[default]#[bold]#{?#{==:#{window_name},window},#{pane_current_command},#W}#[default] "
set -g window-status-separator ""
set -g window-status-current-style "bg=#{@thm_surface_0}"

set -g @custom_text "#[fg=#{@thm_subtext_0}]"
set -g @custom_session_status "#{?client_prefix,"
set -ga @custom_session_status "#[fg=#{@thm_red}]  #[default]#{E:@custom_text}#S ,"
set -ga @custom_session_status "#[fg=#{@thm_mauve}]  #{E:@custom_text}#S }"

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left ""
set -g status-right ""
set -ga status-right "#[fg=#{@thm_blue}] 󰉋 #{E:@custom_text}#{b:pane_current_path} "
set -ga status-right "#{E:@custom_session_status}"

# Load catppuccin
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Colors
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",*256col*:RGB,alacritty:RGB"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
