tap "homebrew/bundle"
tap "homebrew/services"

brew "act"
brew "ansible"
brew "cmake"
brew "composer"
brew "coreutils"
brew "ffmpeg"
brew "git"
brew "gnupg"
brew "go"
brew "hugo"
brew "imagemagick"
brew "neofetch"
brew "neovim"
brew "nmap"
brew "node"
brew "odin"
brew "openssh"
brew "php", restart_service: true
brew "php-cs-fixer"
brew "ripgrep"
brew "starship"
brew "thefuck"
brew "tpm"
brew "tmux"
brew "wp-cli"
brew "yt-dlp"

# Casks
cask "1password"
cask "android-platform-tools"
cask "blackhole-16ch"
cask "docker"
cask "easyfind"
cask "firefox"
cask "firefox@nightly"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "flux"
cask "ghostty"
cask "iterm2"
cask "keka"
cask "omnidisksweeper"
cask "rectangle"
cask "scroll-reverser"
cask "sequel-ace"
cask "spotify"
cask "stats"
cask "transmission"
cask "visual-studio-code"
cask "vlc"
cask "vyprvpn"

# Quicklook plugins
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen" # Might need to fix permissions, see https://github.com/whomwah/qlstephen#permissions-quarantine
cask "qlvideo"
cask "quicklook-json"
cask "quicklookase"
cask "suspicious-package"
