# Colors (Dracula+)

[colors.primary]
background = '#171717'
foreground = '#E0E0DA'

[colors.cursor]
text = '#0E1415'
cursor = '#FFB86C'

[colors.normal]
black = '#21222C'
red = '#FF5555'
green = '#50FA7B'
yellow = '#FFCB6B'
blue = '#82AAFF'
magenta = '#C792EA'
cyan = '#8BE9FD'
white = '#F8F9F2'

[colors.bright]
black = '#545454'
red = '#FF6E6E'
green = '#69FF94'
yellow = '#FFCB6B'
blue = '#D6ACFF'
magenta = '#FF92DF'
cyan = '#A4FFFF'
white = '#F8F8F2'
