[general]
import = [
    "themes/dracula_plus.toml"
]

[font]
normal = { family = "JetbrainsMono Nerd Font Mono", style = "ExtraLight" }
size = 16

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
  { key = "P",  mods = "Control|Shift", chars = "\u001b[80;6u" },
  { key = "N",  mods = "Control|Shift", chars = "\u001b[78;6u" },
]

[env]
TERM = "xterm-256color"
